"""empty message

Revision ID: 3a291af17082
Revises: 639097e787d1
Create Date: 2021-06-26 20:27:52.405064

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_jsonfield
import navycut


# revision identifiers, used by Alembic.
revision = '3a291af17082'
down_revision = '639097e787d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aniket_sarkar',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('picture', navycut.orm.sqla.types.ImageType(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aniket_sarkar')
    # ### end Alembic commands ###