"""empty message

Revision ID: 091bcf66725a
Revises: 9acf5cfedc18
Create Date: 2021-05-15 20:39:52.255457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '091bcf66725a'
down_revision = '9acf5cfedc18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partha', sa.Column('duration', sa.Interval(), nullable=True))
    op.alter_column('partha', 'data',
               existing_type=sqlite.JSON(),
               nullable=False)
    op.alter_column('partha', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('partha', 'profile_image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('suzuka', 'tame',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suzuka', 'tame',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('partha', 'profile_image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('partha', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('partha', 'data',
               existing_type=sqlite.JSON(),
               nullable=True)
    op.drop_column('partha', 'duration')
    # ### end Alembic commands ###
