"""empty message

Revision ID: 0a779a3a60ad
Revises: 1728b8f54720
Create Date: 2021-05-13 18:34:36.994072

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_jsonfield


# revision identifiers, used by Alembic.
revision = '0a779a3a60ad'
down_revision = '1728b8f54720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partha', sa.Column('data', sqlalchemy_jsonfield.jsonfield.JSONField(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partha', 'data')
    # ### end Alembic commands ###
