"""empty message

Revision ID: 19dc4bb16c12
Revises: b556324e5e4d
Create Date: 2021-05-22 20:24:22.089764

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_jsonfield
import navycut
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '19dc4bb16c12'
down_revision = 'b556324e5e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kunal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sqlalchemy_jsonfield.jsonfield.JSONField(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('cycle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('image', navycut.orm.sqla.types.ImageType(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('kunal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kunal_id'], ['kunal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('bike')
    op.drop_table('aniket')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aniket',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('subject', sa.VARCHAR(length=255), nullable=False),
    sa.Column('body', sqlite.JSON(), nullable=True),
    sa.Column('profile_image', sa.VARCHAR(length=255), nullable=False),
    sa.Column('data', sa.VARCHAR(length=255), nullable=False),
    sa.Column('duration', sa.SMALLINT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('bike',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('model', sa.VARCHAR(length=255), nullable=False),
    sa.Column('image', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('aniket_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['aniket_id'], ['aniket.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('cycle')
    op.drop_table('kunal')
    # ### end Alembic commands ###