"""empty message

Revision ID: 1f5bc5eb09cc
Revises: f9f284d1907e
Create Date: 2021-05-12 18:31:04.593057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f5bc5eb09cc'
down_revision = 'f9f284d1907e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nobita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tame', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'tame'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nobita')
    # ### end Alembic commands ###
