"""empty message

Revision ID: 2022008c0f4d
Revises: 38b01b852fa3
Create Date: 2021-05-15 20:49:39.657292

"""
from alembic import op
import sqlalchemy as sa
import navycut
import sqlalchemy_jsonfield
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '2022008c0f4d'
down_revision = '38b01b852fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aniket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('profile_image', navycut.orm.sqla.types.ImageType(length=255), nullable=False),
    sa.Column('data', navycut.orm.sqla.types.ImageType(length=255), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('partha')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partha',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), nullable=False),
    sa.Column('body', sa.VARCHAR(), nullable=False),
    sa.Column('profile_image', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.Column('duration', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('aniket')
    # ### end Alembic commands ###
