"""empty message

Revision ID: 20db5c125805
Revises: 2e5f4fd9684e
Create Date: 2021-05-13 19:10:39.466743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '20db5c125805'
down_revision = '2e5f4fd9684e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partha', 'data',
               existing_type=sqlite.JSON(),
               nullable=False)
    op.alter_column('partha', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('suzuka', 'tame',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suzuka', 'tame',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('partha', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('partha', 'data',
               existing_type=sqlite.JSON(),
               nullable=True)
    # ### end Alembic commands ###
