"""empty message

Revision ID: 56ed08c96c7f
Revises: 790fa2ea124c
Create Date: 2021-05-12 18:42:50.060580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ed08c96c7f'
down_revision = '790fa2ea124c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nobita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tame', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nobita')
    # ### end Alembic commands ###
