"""empty message

Revision ID: 5f9821ee801e
Revises: 1f5bc5eb09cc
Create Date: 2021-05-12 18:40:33.029720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9821ee801e'
down_revision = '1f5bc5eb09cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'nobita', ['tame'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nobita', type_='unique')
    # ### end Alembic commands ###
