"""empty message

Revision ID: 790fa2ea124c
Revises: 5f9821ee801e
Create Date: 2021-05-12 18:42:05.076591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790fa2ea124c'
down_revision = '5f9821ee801e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nobita')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nobita',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tame', sa.VARCHAR(length=255), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), nullable=False),
    sa.Column('body', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'tame'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###
