"""empty message

Revision ID: 83378a8c4ebe
Revises: e544e91f7bf0
Create Date: 2021-05-12 18:46:51.993066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83378a8c4ebe'
down_revision = 'e544e91f7bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nobita')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nobita',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tame', sa.VARCHAR(length=255), nullable=True),
    sa.Column('subject', sa.VARCHAR(length=255), nullable=False),
    sa.Column('body', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###
