"""empty message

Revision ID: 9acf5cfedc18
Revises: 20db5c125805
Create Date: 2021-05-13 19:13:00.695430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '9acf5cfedc18'
down_revision = '20db5c125805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partha', 'data',
               existing_type=sqlite.JSON(),
               nullable=False)
    op.alter_column('partha', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('suzuka', 'tame',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suzuka', 'tame',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('partha', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('partha', 'data',
               existing_type=sqlite.JSON(),
               nullable=True)
    # ### end Alembic commands ###
