"""empty message

Revision ID: a07a6c7a226e
Revises: c047d24c6444
Create Date: 2021-05-15 20:40:53.570732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'a07a6c7a226e'
down_revision = 'c047d24c6444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aniket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('profile_image', navycut.orm.sqla.types.ImageType(length=255), nullable=False),
    sa.Column('data', navycut.orm.sqla.types.ImageType(length=255), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.alter_column('partha', 'data',
               existing_type=sqlite.JSON(),
               nullable=False)
    op.alter_column('partha', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('partha', 'profile_image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partha', 'profile_image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('partha', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('partha', 'data',
               existing_type=sqlite.JSON(),
               nullable=True)
    op.drop_table('aniket')
    # ### end Alembic commands ###
