"""empty message

Revision ID: b556324e5e4d
Revises: 
Create Date: 2021-05-22 20:18:39.528980

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_jsonfield
import navycut


# revision identifiers, used by Alembic.
revision = 'b556324e5e4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aniket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sqlalchemy_jsonfield.jsonfield.JSONField(), nullable=True),
    sa.Column('profile_image', navycut.orm.sqla.types.ImageType(length=255), nullable=False),
    sa.Column('data', navycut.orm.sqla.types.ImageType(length=255), nullable=False),
    sa.Column('duration', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('bike',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('image', navycut.orm.sqla.types.ImageType(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('aniket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aniket_id'], ['aniket.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('group_user_con',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['group.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_user_con')
    op.drop_table('bike')
    op.drop_table('user')
    op.drop_table('group')
    op.drop_table('aniket')
    # ### end Alembic commands ###