"""empty message

Revision ID: c047d24c6444
Revises: 091bcf66725a
Create Date: 2021-05-15 20:40:17.917626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'c047d24c6444'
down_revision = '091bcf66725a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suzuka')
    op.drop_table('doraemon')
    op.drop_table('kiteretsu')
    op.drop_table('blogs')
    op.drop_table('motu_patlu')
    op.alter_column('partha', 'data',
               existing_type=sqlite.JSON(),
               nullable=False)
    op.alter_column('partha', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('partha', 'profile_image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partha', 'profile_image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('partha', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('partha', 'data',
               existing_type=sqlite.JSON(),
               nullable=True)
    op.create_table('motu_patlu',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), nullable=False),
    sa.Column('body', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('blogs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), nullable=False),
    sa.Column('body', sa.VARCHAR(), nullable=False),
    sa.Column('head_image', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('kiteretsu',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), nullable=False),
    sa.Column('body', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'name'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('doraemon',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), nullable=False),
    sa.Column('body', sa.VARCHAR(), nullable=False),
    sa.Column('head_image', sa.VARCHAR(length=255), nullable=True),
    sa.Column('body_picture', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('suzuka',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tame', sa.VARCHAR(length=255), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), nullable=False),
    sa.Column('body', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###
