"""empty message

Revision ID: c729fb8f579c
Revises: 19dc4bb16c12
Create Date: 2021-05-22 20:30:58.801741

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_jsonfield
import navycut
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'c729fb8f579c'
down_revision = '19dc4bb16c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sqlalchemy_jsonfield.jsonfield.JSONField(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('kunal')
    op.drop_constraint(None, 'cycle', type_='foreignkey')
    op.create_foreign_key(None, 'cycle', 'owner', ['kunal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cycle', type_='foreignkey')
    op.create_foreign_key(None, 'cycle', 'kunal', ['kunal_id'], ['id'])
    op.create_table('kunal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('subject', sa.VARCHAR(length=255), nullable=False),
    sa.Column('body', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('owner')
    # ### end Alembic commands ###