"""empty message

Revision ID: e544e91f7bf0
Revises: 56ed08c96c7f
Create Date: 2021-05-12 18:45:55.386766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e544e91f7bf0'
down_revision = '56ed08c96c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suzuka',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tame', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.alter_column('nobita', 'tame',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nobita', 'tame',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_table('suzuka')
    # ### end Alembic commands ###
