"""empty message

Revision ID: e209fa913dc6
Revises: 9f34316d5827
Create Date: 2022-02-19 12:15:05.406211

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_jsonfield
import navycut


# revision identifiers, used by Alembic.
revision = 'e209fa913dc6'
down_revision = '9f34316d5827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('author', 'picture',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('author', 'picture',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###